k8s_modules_conf_path: /etc/modules-load.d/k8s.conf
k8s_kernel_modules:
  - overlay
  - br_netfilter

k8s_sysctl_conf_path: /etc/sysctl.d/k8s.conf
k8s_sysctl_settings:
  net.bridge.bridge-nf-call-ip6tables: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1

k8s_fstab_path: /etc/fstab
k8s_swap_regexp: '^(.*\s+swap\s+.*)$'
